<?php
  // session_start();
  require 'dbh.inc.php';
  $mail = $_SESSION['usermail'];
  $vehiclenamearray = [];
  $vehicleregnoarray = [];
  $deliverytypearray = [];
  $requestdatearray = [];
  $servicestatusarray = [];

  $row1serviceno = "";
  $row1vehiclename = "";
  $row1vehicleregno = "";
  $row1deliverytype = "";
  $row1requestdate = "";
  $row1servicestatus = "";

  $row2serviceno = "";
  $row2vehiclename = "";
  $row2vehicleregno = "";
  $row2deliverytype = "";
  $row2requestdate = "";
  $row2servicestatus = "";

  $row3serviceno = "";
  $row3vehiclename = "";
  $row3vehicleregno = "";
  $row3deliverytype = "";
  $row3requestdate = "";
  $row3servicestatus = "";

  $row4serviceno = "";
  $row4vehiclename = "";
  $row4vehicleregno = "";
  $row4deliverytype = "";
  $row4requestdate = "";
  $row4servicestatus = "";

  $row5serviceno = "";
  $row5vehiclename = "";
  $row5vehicleregno = "";
  $row5deliverytype = "";
  $row5requestdate = "";
  $row5servicestatus = "";

  $row6serviceno = "";
  $row6vehiclename = "";
  $row6vehicleregno = "";
  $row6deliverytype = "";
  $row6requestdate = "";
  $row6servicestatus = "";

  $row7serviceno = "";
  $row7vehiclename = "";
  $row7vehicleregno = "";
  $row7deliverytype = "";
  $row7requestdate = "";
  $row7servicestatus = "";

  $row8serviceno = "";
  $row8vehiclename = "";
  $row8vehicleregno = "";
  $row8deliverytype = "";
  $row8requestdate = "";
  $row8servicestatus = "";

  $row9serviceno = "";
  $row9vehiclename = "";
  $row9vehicleregno = "";
  $row9deliverytype = "";
  $row9requestdate = "";
  $row9servicestatus = "";

  $row10serviceno = "";
  $row10vehiclename = "";
  $row10vehicleregno = "";
  $row10deliverytype = "";
  $row10requestdate = "";
  $row10servicestatus = "";

  $sql = "SELECT * FROM services WHERE request_email=?";
  $stmt = mysqli_stmt_init($conn);
  if (!mysqli_stmt_prepare($stmt, $sql)) {
    header("Location: ../service-history.php?error=sqlerror");
    exit();
  }
  else {
    mysqli_stmt_bind_param($stmt, "s", $mail);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);

    while ($row = mysqli_fetch_assoc($result)) {
      array_push($vehicleregnoarray, $row['vehicle_regno']);
      array_push($vehiclenamearray, $row['vehicle_name']);
      array_push($deliverytypearray, $row['delivery_type']);
      array_push($requestdatearray, $row['service_date']);
      array_push($servicestatusarray, $row['service_status']);
    }
    $rowcount = count($vehiclenamearray);
    if ($rowcount == 1) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
    }
    else if ($rowcount == 2) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
    }
    else if ($rowcount == 3) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
    }
    else if ($rowcount == 4) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
    }
    else if ($rowcount == 5) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
      $row5serviceno = 5;
      $row5vehiclename = $vehiclenamearray[4];
      $row5vehicleregno = $vehicleregnoarray[4];
      $row5deliverytype = $deliverytypearray[4];
      $row5requestdate = $requestdatearray[4];
      $row5servicestatus = $servicestatusarray[4];
    }
    else if ($rowcount == 6) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
      $row5serviceno = 5;
      $row5vehiclename = $vehiclenamearray[4];
      $row5vehicleregno = $vehicleregnoarray[4];
      $row5deliverytype = $deliverytypearray[4];
      $row5requestdate = $requestdatearray[4];
      $row5servicestatus = $servicestatusarray[4];
      $row6serviceno = 6;
      $row6vehiclename = $vehiclenamearray[5];
      $row6vehicleregno = $vehicleregnoarray[5];
      $row6deliverytype = $deliverytypearray[5];
      $row6requestdate = $requestdatearray[5];
      $row6servicestatus = $servicestatusarray[5];
    }
    else if ($rowcount == 7) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
      $row5serviceno = 5;
      $row5vehiclename = $vehiclenamearray[4];
      $row5vehicleregno = $vehicleregnoarray[4];
      $row5deliverytype = $deliverytypearray[4];
      $row5requestdate = $requestdatearray[4];
      $row5servicestatus = $servicestatusarray[4];
      $row6serviceno = 6;
      $row6vehiclename = $vehiclenamearray[5];
      $row6vehicleregno = $vehicleregnoarray[5];
      $row6deliverytype = $deliverytypearray[5];
      $row6requestdate = $requestdatearray[5];
      $row6servicestatus = $servicestatusarray[5];
      $row7serviceno = 7;
      $row7vehiclename = $vehiclenamearray[6];
      $row7vehicleregno = $vehicleregnoarray[6];
      $row7deliverytype = $deliverytypearray[6];
      $row7requestdate = $requestdatearray[6];
      $row7servicestatus = $servicestatusarray[6];
    }
    else if ($rowcount == 8) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
      $row5serviceno = 5;
      $row5vehiclename = $vehiclenamearray[4];
      $row5vehicleregno = $vehicleregnoarray[4];
      $row5deliverytype = $deliverytypearray[4];
      $row5requestdate = $requestdatearray[4];
      $row5servicestatus = $servicestatusarray[4];
      $row6serviceno = 6;
      $row6vehiclename = $vehiclenamearray[5];
      $row6vehicleregno = $vehicleregnoarray[5];
      $row6deliverytype = $deliverytypearray[5];
      $row6requestdate = $requestdatearray[5];
      $row6servicestatus = $servicestatusarray[5];
      $row7serviceno = 7;
      $row7vehiclename = $vehiclenamearray[6];
      $row7vehicleregno = $vehicleregnoarray[6];
      $row7deliverytype = $deliverytypearray[6];
      $row7requestdate = $requestdatearray[6];
      $row7servicestatus = $servicestatusarray[6];
      $row8serviceno = 8;
      $row8vehiclename = $vehiclenamearray[7];
      $row8vehicleregno = $vehicleregnoarray[7];
      $row8deliverytype = $deliverytypearray[7];
      $row8requestdate = $requestdatearray[7];
      $row8servicestatus = $servicestatusarray[7];
    }
    else if ($rowcount == 9) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
      $row5serviceno = 5;
      $row5vehiclename = $vehiclenamearray[4];
      $row5vehicleregno = $vehicleregnoarray[4];
      $row5deliverytype = $deliverytypearray[4];
      $row5requestdate = $requestdatearray[4];
      $row5servicestatus = $servicestatusarray[4];
      $row6serviceno = 6;
      $row6vehiclename = $vehiclenamearray[5];
      $row6vehicleregno = $vehicleregnoarray[5];
      $row6deliverytype = $deliverytypearray[5];
      $row6requestdate = $requestdatearray[5];
      $row6servicestatus = $servicestatusarray[5];
      $row7serviceno = 7;
      $row7vehiclename = $vehiclenamearray[6];
      $row7vehicleregno = $vehicleregnoarray[6];
      $row7deliverytype = $deliverytypearray[6];
      $row7requestdate = $requestdatearray[6];
      $row7servicestatus = $servicestatusarray[6];
      $row8serviceno = 8;
      $row8vehiclename = $vehiclenamearray[7];
      $row8vehicleregno = $vehicleregnoarray[7];
      $row8deliverytype = $deliverytypearray[7];
      $row8requestdate = $requestdatearray[7];
      $row8servicestatus = $servicestatusarray[7];
      $row9serviceno = 9;
      $row9vehiclename = $vehiclenamearray[8];
      $row9vehicleregno = $vehicleregnoarray[8];
      $row9deliverytype = $deliverytypearray[8];
      $row9requestdate = $requestdatearray[8];
      $row9servicestatus = $servicestatusarray[8];
    }
    else if ($rowcount == 10) {
      $row1serviceno = 1;
      $row1vehiclename = $vehiclenamearray[0];
      $row1vehicleregno = $vehicleregnoarray[0];
      $row1deliverytype = $deliverytypearray[0];
      $row1requestdate = $requestdatearray[0];
      $row1servicestatus = $servicestatusarray[0];
      $row2serviceno = 2;
      $row2vehiclename = $vehiclenamearray[1];
      $row2vehicleregno = $vehicleregnoarray[1];
      $row2deliverytype = $deliverytypearray[1];
      $row2requestdate = $requestdatearray[1];
      $row2servicestatus = $servicestatusarray[1];
      $row3serviceno = 3;
      $row3vehiclename = $vehiclenamearray[2];
      $row3vehicleregno = $vehicleregnoarray[2];
      $row3deliverytype = $deliverytypearray[2];
      $row3requestdate = $requestdatearray[2];
      $row3servicestatus = $servicestatusarray[2];
      $row4serviceno = 4;
      $row4vehiclename = $vehiclenamearray[3];
      $row4vehicleregno = $vehicleregnoarray[3];
      $row4deliverytype = $deliverytypearray[3];
      $row4requestdate = $requestdatearray[3];
      $row4servicestatus = $servicestatusarray[3];
      $row5serviceno = 5;
      $row5vehiclename = $vehiclenamearray[4];
      $row5vehicleregno = $vehicleregnoarray[4];
      $row5deliverytype = $deliverytypearray[4];
      $row5requestdate = $requestdatearray[4];
      $row5servicestatus = $servicestatusarray[4];
      $row6serviceno = 6;
      $row6vehiclename = $vehiclenamearray[5];
      $row6vehicleregno = $vehicleregnoarray[5];
      $row6deliverytype = $deliverytypearray[5];
      $row6requestdate = $requestdatearray[5];
      $row6servicestatus = $servicestatusarray[5];
      $row7serviceno = 7;
      $row7vehiclename = $vehiclenamearray[6];
      $row7vehicleregno = $vehicleregnoarray[6];
      $row7deliverytype = $deliverytypearray[6];
      $row7requestdate = $requestdatearray[6];
      $row7servicestatus = $servicestatusarray[6];
      $row8serviceno = 8;
      $row8vehiclename = $vehiclenamearray[7];
      $row8vehicleregno = $vehicleregnoarray[7];
      $row8deliverytype = $deliverytypearray[7];
      $row8requestdate = $requestdatearray[7];
      $row8servicestatus = $servicestatusarray[7];
      $row9serviceno = 9;
      $row9vehiclename = $vehiclenamearray[8];
      $row9vehicleregno = $vehicleregnoarray[8];
      $row9deliverytype = $deliverytypearray[8];
      $row9requestdate = $requestdatearray[8];
      $row9servicestatus = $servicestatusarray[8];
      $row10serviceno = 10;
      $row10vehiclename = $vehiclenamearray[9];
      $row10vehicleregno = $vehicleregnoarray[9];
      $row10deliverytype = $deliverytypearray[9];
      $row10requestdate = $requestdatearray[9];
      $row10servicestatus = $servicestatusarray[9];
    }
  }
